// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHo3z0esGgoNcSTn5LfzfyRYsOcMphwk',
    appId: '1:616174026379:android:bcf44195105ae432285e8e',
    messagingSenderId: '616174026379',
    projectId: 'fir-fb56f',
    databaseURL: 'https://fir-fb56f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fb56f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJF_R_3D73idOiyocdrJBAaNLuCRH2zw',
    appId: '1:616174026379:ios:762fc73c1fb41556285e8e',
    messagingSenderId: '616174026379',
    projectId: 'fir-fb56f',
    databaseURL: 'https://fir-fb56f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fb56f.appspot.com',
    androidClientId: '616174026379-5u95msvt04isjgn1kvbh6ovrq7b4udfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooodie',
  );
}
